[package]
name = "proof_engine_test"
edition.workspace = true
version.workspace = true

[dependencies]
simulator = { path = "../simulator", features = ["test-utils"] }
network = { workspace = true, features = ["disable-backfill"] }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }

