[workspace]
members = ["."]
resolver = "2"

[workspace.dependencies]
zkboost-server = { git = "https://github.com/eth-act/zkboost", branch = "master" }
zkboost-types = { git = "https://github.com/eth-act/zkboost", branch = "master" }

[package]
name = "proof_engine_zkboost_test"
version = "0.1.0"
edition = "2024"

[features]
portable = ["types/portable"]

[dependencies]
anyhow = "1"
axum = "0.7"
bytes = "1"
ethereum_ssz = { version = "0.10.0", features = ["context_deserialize"] }
execution_layer = { path = "../../beacon_node/execution_layer" }
futures = "0.3"
metrics-exporter-prometheus = "0.16"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "stream", "rustls-tls"] }
sensitive_url = { version = "0.1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ssz_types = { version = "0.14.0", features = ["context_deserialize", "runtime_types"] }
strum = { version = "0.27", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "signal", "macros"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-util = { version = "0.7", features = ["codec", "compat", "time"] }
tracing = "0.1"
tree_hash = "0.12.0"
types = { path = "../../consensus/types" }
url = "2"
zkboost-server = { workspace = true }
zkboost-types = { workspace = true }
