[package]
name = "proof_engine"
version = "0.1.0"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[dependencies]
ere-catalog = { workspace = true }
ere-verifier = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tree_hash = { workspace = true }
types = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
