[package]
name = "zkvm_execution_layer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1" #TODO(zkproofs): Remove
execution_layer = { path = "../beacon_node/execution_layer" }
hashbrown = "0.15"
lru = "0.12"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = ["full"] }
types = { path = "../consensus/types" }

[dev-dependencies]
