//! Topology and lifecycle of the proof test network.

use crate::{E, NodeChain, ProvenPayload, ProverSpec, ProvingExecutionLayer};
use node_test_rig::{
    ClientConfig, LocalExecutionNode, MockExecutionConfig, ValidatorFiles,
    environment::{EnvironmentBuilder, RuntimeContext},
    eth2::BeaconNodeHttpClient,
    testing_validator_config,
};
use proof_engine::{ProofEngine, ProofEngineConfig, test_utils::MockProofEngine};
use sensitive_url::SensitiveUrl;
use simulator::local_network::{EXECUTION_PORT, LocalNetwork, LocalNetworkParams};
use std::{
    future::Future,
    sync::{Arc, Mutex},
    time::Duration,
};
use tracing::info;
use tracing_subscriber::EnvFilter;
use types::{Address, ChainSpec, Epoch};

/// Fee recipient configured for every validator client, as in the simulator.
const FEE_RECIPIENT: [u8; 20] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1];

/// Node log filter used when `RUST_LOG` is unset.
const DEFAULT_LOG_FILTER: &str = "warn,execution_proof_network_tests=info";

/// Serialises networks within one process: every node binds the simulator's fixed ports.
static NETWORK_LOCK: Mutex<()> = Mutex::new(());

/// Port offsets, above the simulator's own execution ports, for the mock execution layer and
/// the proving proxy of a proving node.
const PROVING_MOCK_PORT_OFFSET: u16 = 1000;
const PROVING_PROXY_PORT_OFFSET: u16 = 2000;

/// Configuration of one beacon node in the network.
///
/// A node validates execution with its (mock) execution layer, with a proof engine, or both:
///
/// - [`NodeSpec::plain`]: execution layer only. Imports payloads as soon as they are executed and
///   never joins the `execution_proof` topic.
/// - [`NodeSpec::verifier`]: execution layer and proof engine. Imports payloads as soon as they
///   are executed, and verifies and caches proofs without holding the payload back.
/// - [`NodeSpec::proof_only`]: proof engine only. Holds every payload in the pending payload
///   cache until two proof types verify, and cannot build payloads, so it cannot carry
///   validators.
///
/// A verifier can also prove: [`NodeSpec::proving`] puts a [`ProvingExecutionLayer`] between
/// the node and its mock execution layer, so every payload the node executes is proved and
/// the proofs are posted to the node's Beacon API.
#[derive(Debug, Clone)]
pub struct NodeSpec {
    /// Proof data accepted by this node's mock proof engine. `None` starts the node without a
    /// proof engine: it neither verifies proofs nor subscribes to the `execution_proof` topic.
    pub valid_proof_data: Option<Vec<Vec<u8>>>,
    /// Whether the node is paired with a mock execution layer.
    pub execution_layer: bool,
    /// Whether a validator client is attached to this node.
    pub validators: bool,
    /// Proofs generated by a proving execution layer in front of this node's mock execution
    /// layer.
    pub prover: Option<ProverSpec>,
    /// Start the mock execution layer answering `SYNCING` to every `engine_newPayload`.
    pub execution_layer_syncing: bool,
}

impl NodeSpec {
    /// A node with an execution layer and no proof engine.
    pub fn plain() -> Self {
        Self {
            valid_proof_data: None,
            execution_layer: true,
            validators: false,
            prover: None,
            execution_layer_syncing: false,
        }
    }

    /// A node with an execution layer and a mock proof engine accepting exactly
    /// `valid_proof_data`.
    pub fn verifier(valid_proof_data: impl IntoIterator<Item = Vec<u8>>) -> Self {
        Self {
            valid_proof_data: Some(valid_proof_data.into_iter().collect()),
            execution_layer: true,
            validators: false,
            prover: None,
            execution_layer_syncing: false,
        }
    }

    /// A node without an execution layer whose mock proof engine accepts exactly
    /// `valid_proof_data`. Its payload imports wait for proofs.
    pub fn proof_only(valid_proof_data: impl IntoIterator<Item = Vec<u8>>) -> Self {
        Self {
            valid_proof_data: Some(valid_proof_data.into_iter().collect()),
            execution_layer: false,
            validators: false,
            prover: None,
            execution_layer_syncing: false,
        }
    }

    /// Attach a validator client to this node. Requires an execution layer.
    pub fn with_validators(mut self) -> Self {
        self.validators = true;
        self
    }

    /// Prove every payload this node executes. Requires an execution layer and a proof engine,
    /// since the proofs are posted to this node's Beacon API.
    pub fn proving(mut self, prover: ProverSpec) -> Self {
        self.prover = Some(prover);
        self
    }

    /// Start with the mock execution layer syncing: `engine_newPayload` answers `SYNCING` until
    /// [`ProofNetwork::set_execution_layer_syncing`] turns it off. Requires an execution layer.
    pub fn with_syncing_execution_layer(mut self) -> Self {
        self.execution_layer_syncing = true;
        self
    }

    pub fn has_proof_engine(&self) -> bool {
        self.valid_proof_data.is_some()
    }

    /// Short label for diagnostics.
    pub fn mode(&self) -> &'static str {
        match (
            self.execution_layer,
            self.has_proof_engine(),
            self.prover.is_some(),
        ) {
            (true, false, _) => "execution-layer",
            (true, true, false) => "verifier",
            (true, true, true) => "proving verifier",
            (false, true, _) => "proof-only",
            (false, false, _) => "invalid",
        }
    }
}

/// Network-wide parameters.
#[derive(Debug, Clone)]
pub struct ProofNetworkConfig {
    /// Nodes to start, in index order. The first node is the boot node.
    pub nodes: Vec<NodeSpec>,
    /// Genesis validators, split evenly across the nodes with `validators` set.
    pub validator_count: usize,
    pub slot_duration_ms: u64,
    /// Seconds between network start and genesis; must cover node and validator startup.
    pub genesis_delay_secs: u64,
    /// All earlier forks activate at genesis. Execution proofs exist from Gloas onwards.
    pub gloas_fork_epoch: u64,
    /// Node log filter, overridden by `RUST_LOG`.
    pub log_filter: String,
}

impl ProofNetworkConfig {
    /// Defaults tuned for release builds: 2-second slots, Gloas at genesis and a genesis delay
    /// long enough to start the nodes and validators. Gloas genesis needs a validator in every
    /// slot's beacon committee (the payload timeliness committee is drawn from it), so the
    /// validator count stays at two per minimal-spec slot.
    pub fn new(nodes: Vec<NodeSpec>) -> Self {
        Self {
            nodes,
            validator_count: 16,
            slot_duration_ms: 2000,
            genesis_delay_secs: 30,
            gloas_fork_epoch: 0,
            log_filter: DEFAULT_LOG_FILTER.to_string(),
        }
    }
}

/// A running network of beacon nodes with per-node execution layers and proof engines.
pub struct ProofNetwork {
    pub(crate) network: LocalNetwork<E>,
    nodes: Vec<NodeSpec>,
    spec: Arc<ChainSpec>,
    context: RuntimeContext<E>,
    base_config: ClientConfig,
    execution_config: MockExecutionConfig,
    /// Proving execution layers by node index.
    provers: Vec<(usize, ProvingExecutionLayer)>,
    /// Mock execution layers owned by proving nodes (the simulator owns the others).
    proving_execution_nodes: Vec<LocalExecutionNode<E>>,
    /// Where each node's mock execution layer lives, by node index.
    execution_layers: Vec<Option<MockExecutionLayer>>,
}

/// Which collection holds a node's mock execution layer.
#[derive(Debug, Clone, Copy)]
enum MockExecutionLayer {
    /// Index into the simulator's `execution_nodes`.
    Simulator(usize),
    /// Index into the harness's proving execution nodes.
    Proving(usize),
}

impl ProofNetwork {
    /// Start the network, run `test` on the environment's runtime, then tear everything down.
    ///
    /// Follows the simulator lifecycle: one multi-threaded tokio runtime per network, nodes
    /// added through [`LocalNetwork`], and the runtime shut down once the test returns. Networks
    /// are serialised process-wide because nodes bind fixed ports.
    pub fn run<F, Fut>(config: ProofNetworkConfig, test: F) -> Result<(), String>
    where
        F: FnOnce(ProofNetwork) -> Fut,
        Fut: Future<Output = Result<(), String>>,
    {
        let _serial = NETWORK_LOCK
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());
        init_tracing(&config.log_filter);

        let mut env = EnvironmentBuilder::minimal()
            .multi_threaded_tokio_runtime()?
            .build()?;
        let spec = Arc::new(chain_spec(&env.eth2_config.spec, &config));
        env.eth2_config.spec = spec.clone();
        let context = env.core_context();

        let result = env.runtime().block_on(async {
            let network = Self::build(config, spec, context).await?;
            test(network).await
        });

        env.fire_signal();
        env.shutdown_on_idle();
        result
    }

    async fn build(
        config: ProofNetworkConfig,
        spec: Arc<ChainSpec>,
        context: RuntimeContext<E>,
    ) -> Result<Self, String> {
        let ProofNetworkConfig {
            nodes,
            validator_count,
            genesis_delay_secs,
            ..
        } = config;
        if nodes.is_empty() {
            return Err("a proof network needs at least one node".to_string());
        }

        let params = LocalNetworkParams {
            validator_count,
            node_count: nodes.len(),
            proposer_nodes: 0,
            extra_nodes: 0,
            genesis_delay: genesis_delay_secs,
        };
        // Node start-up futures are large; box them so `build` keeps a small stack frame.
        let (network, base_config, execution_config) = Box::pin(
            LocalNetwork::create_local_network(None, None, params, context.clone()),
        )
        .await?;

        let mut net = Self {
            network,
            nodes: Vec::with_capacity(nodes.len()),
            spec,
            context,
            base_config,
            execution_config,
            provers: Vec::new(),
            proving_execution_nodes: Vec::new(),
            execution_layers: Vec::new(),
        };
        for node in nodes {
            net.start_node(node).await?;
        }

        let validator_nodes = net.nodes_where(|node| node.validators);
        for (position, node_index) in validator_nodes.iter().enumerate() {
            let per_node = validator_count / validator_nodes.len();
            let start = position * per_node;
            let end = if position + 1 == validator_nodes.len() {
                validator_count
            } else {
                start + per_node
            };
            let indices: Vec<usize> = (start..end).collect();
            info!(node = node_index, validators = ?indices, "Starting validator client");
            let files = net
                .context
                .executor
                .spawn_blocking_handle(
                    move || ValidatorFiles::with_keystores(&indices),
                    "validator_keystore_generation",
                )
                .ok_or("runtime is shutting down")?
                .await
                .map_err(|e| format!("keystore generation panicked: {e:?}"))??;
            let mut validator_config = testing_validator_config();
            validator_config.validator_store.fee_recipient = Some(Address::from(FEE_RECIPIENT));
            Box::pin(
                net.network
                    .add_validator_client(validator_config, *node_index, files),
            )
            .await?;
        }

        Ok(net)
    }

    /// Start another beacon node once the network is running, for late-joining scenarios. It
    /// connects through the boot node and syncs like any other late node. Validators cannot be
    /// attached this way: the genesis validator set is fixed when the network is built.
    pub async fn add_node(&mut self, node: NodeSpec) -> Result<usize, String> {
        if node.validators {
            return Err("validators can only be attached to nodes started with the network".into());
        }
        self.start_node(node).await
    }

    async fn start_node(&mut self, node: NodeSpec) -> Result<usize, String> {
        let index = self.nodes.len();
        if !node.execution_layer && !node.has_proof_engine() {
            return Err(format!(
                "node {index} needs an execution layer or a proof engine"
            ));
        }
        if node.validators && !node.execution_layer {
            return Err(format!(
                "node {index} cannot carry validators without an execution layer"
            ));
        }
        if node.prover.is_some() && !(node.execution_layer && node.has_proof_engine()) {
            return Err(format!(
                "node {index} needs an execution layer and a proof engine to prove payloads"
            ));
        }
        if node.execution_layer_syncing && !node.execution_layer {
            return Err(format!(
                "node {index} has no execution layer to put into syncing"
            ));
        }

        let mut client_config = self.base_config.clone();
        configure_proof_engine(&mut client_config, &node);
        info!(
            node = index,
            mode = node.mode(),
            validators = node.validators,
            "Starting beacon node"
        );
        match (&node.prover, node.execution_layer) {
            (Some(prover), _) => {
                // The node talks to the proving proxy, which forwards to its own mock.
                let mut mock_config = self.execution_config.clone();
                mock_config.server_config.listen_port =
                    EXECUTION_PORT + PROVING_MOCK_PORT_OFFSET + index as u16;
                let execution_node = LocalExecutionNode::new(self.context.clone(), mock_config);
                let handle = self
                    .context
                    .executor
                    .handle()
                    .ok_or("runtime is shutting down")?;
                let proving = ProvingExecutionLayer::start(
                    &handle,
                    EXECUTION_PORT + PROVING_PROXY_PORT_OFFSET + index as u16,
                    execution_node.server.url(),
                    self.spec.clone(),
                    prover.clone(),
                )?;
                client_config.execution_layer = Some(execution_layer::Config {
                    execution_endpoint: Some(
                        SensitiveUrl::parse(&proving.url())
                            .map_err(|e| format!("invalid proving proxy url: {e:?}"))?,
                    ),
                    default_datadir: execution_node.datadir.path().to_path_buf(),
                    secret_file: Some(execution_node.datadir.path().join("jwt.hex")),
                    ..Default::default()
                });
                Box::pin(
                    self.network
                        .add_beacon_node_without_mock_execution_layer(client_config, false),
                )
                .await?;
                proving.set_target(self.remote_node(index)?);
                execution_node.server.all_payloads_valid();
                self.provers.push((index, proving));
                self.proving_execution_nodes.push(execution_node);
                self.execution_layers.push(Some(MockExecutionLayer::Proving(
                    self.proving_execution_nodes.len() - 1,
                )));
            }
            (None, true) => {
                Box::pin(self.network.add_beacon_node(
                    client_config,
                    self.execution_config.clone(),
                    false,
                ))
                .await?;
                // The simulator owns this mock execution layer; it is infallible too.
                let execution_nodes = self.network.execution_nodes.read();
                execution_nodes
                    .iter()
                    .for_each(|node| node.server.all_payloads_valid());
                self.execution_layers
                    .push(Some(MockExecutionLayer::Simulator(
                        execution_nodes.len() - 1,
                    )));
            }
            (None, false) => {
                client_config.execution_layer = None;
                Box::pin(
                    self.network
                        .add_beacon_node_without_mock_execution_layer(client_config, false),
                )
                .await?;
                self.execution_layers.push(None);
            }
        }
        let syncing = node.execution_layer_syncing;
        self.nodes.push(node);
        if syncing {
            self.set_execution_layer_syncing(index, true)?;
        }
        Ok(index)
    }

    /// Make node `node`'s mock execution layer answer `SYNCING` (or `VALID` again) to every
    /// `engine_newPayload` and `engine_forkchoiceUpdated`.
    pub fn set_execution_layer_syncing(&self, node: usize, syncing: bool) -> Result<(), String> {
        let mock = self
            .execution_layers
            .get(node)
            .copied()
            .flatten()
            .ok_or(format!("node {node} has no mock execution layer"))?;
        let apply = |server: &node_test_rig::MockServer<E>| {
            if syncing {
                server.all_payloads_syncing(false);
            } else {
                server.all_payloads_valid();
            }
        };
        match mock {
            MockExecutionLayer::Simulator(index) => {
                let execution_nodes = self.network.execution_nodes.read();
                apply(&execution_nodes.get(index).ok_or("missing mock")?.server);
            }
            MockExecutionLayer::Proving(index) => {
                apply(
                    &self
                        .proving_execution_nodes
                        .get(index)
                        .ok_or("missing mock")?
                        .server,
                );
            }
        }
        info!(node, syncing, "Set mock execution layer sync state");
        Ok(())
    }

    /// Payloads proved so far by node `node`'s proving execution layer, in submission order.
    pub fn proven_payloads(&self, node: usize) -> Result<Vec<ProvenPayload>, String> {
        self.provers
            .iter()
            .find(|(index, _)| *index == node)
            .map(|(_, proving)| proving.proven_payloads())
            .ok_or(format!("node {node} has no proving execution layer"))
    }

    pub fn node_count(&self) -> usize {
        self.nodes.len()
    }

    pub fn node_spec(&self, node: usize) -> Result<&NodeSpec, String> {
        self.nodes.get(node).ok_or(format!("no node {node}"))
    }

    /// Indices of the nodes for which `predicate` holds.
    pub fn nodes_where(&self, predicate: impl Fn(&NodeSpec) -> bool) -> Vec<usize> {
        self.nodes
            .iter()
            .enumerate()
            .filter(|(_, node)| predicate(node))
            .map(|(index, _)| index)
            .collect()
    }

    pub fn spec(&self) -> &ChainSpec {
        &self.spec
    }

    pub fn slot_duration(&self) -> Duration {
        self.spec.get_slot_duration()
    }

    /// The underlying simulator network, for scenarios the harness does not cover.
    pub fn local_network(&self) -> &LocalNetwork<E> {
        &self.network
    }

    /// The beacon chain of node `node`.
    pub fn chain(&self, node: usize) -> Result<NodeChain, String> {
        self.network
            .beacon_nodes
            .read()
            .get(node)
            .ok_or(format!("no node {node}"))?
            .client
            .beacon_chain()
            .ok_or(format!("node {node} has no beacon chain"))
    }

    /// An HTTP client for node `node`'s Beacon API.
    pub fn remote_node(&self, node: usize) -> Result<BeaconNodeHttpClient, String> {
        self.network
            .beacon_nodes
            .read()
            .get(node)
            .ok_or(format!("no node {node}"))?
            .remote_node()
    }

    /// Sleep until genesis. Returns immediately if genesis has passed.
    pub async fn wait_for_genesis(&self) -> Result<(), String> {
        match self.network.duration_to_genesis().await {
            Ok(duration) => {
                info!(seconds = duration.as_secs(), "Waiting for genesis");
                tokio::time::sleep(duration).await;
            }
            Err(reason) => info!(reason, "Genesis has already passed"),
        }
        Ok(())
    }
}

fn configure_proof_engine(client_config: &mut ClientConfig, node: &NodeSpec) {
    if let Some(valid_proof_data) = &node.valid_proof_data {
        let engine = ProofEngine::new(MockProofEngine::new(valid_proof_data.iter().cloned()));
        client_config.proof_engine = Some(ProofEngineConfig::default().with_engine(engine));
        client_config.network.enable_execution_proof = true;
    }
}

fn chain_spec(base: &ChainSpec, config: &ProofNetworkConfig) -> ChainSpec {
    let mut spec = base
        .clone()
        .set_slot_duration_ms::<E>(config.slot_duration_ms);
    spec.genesis_delay = config.genesis_delay_secs;
    spec.min_genesis_time = 0;
    spec.min_genesis_active_validator_count = config.validator_count as u64;
    let genesis = Some(Epoch::new(0));
    spec.altair_fork_epoch = genesis;
    spec.bellatrix_fork_epoch = genesis;
    spec.capella_fork_epoch = genesis;
    spec.deneb_fork_epoch = genesis;
    spec.electra_fork_epoch = genesis;
    spec.fulu_fork_epoch = genesis;
    spec.gloas_fork_epoch = Some(Epoch::new(config.gloas_fork_epoch));
    spec
}

fn init_tracing(default_filter: &str) {
    let filter =
        EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new(default_filter));
    let _ = tracing_subscriber::fmt()
        .with_env_filter(filter)
        .with_test_writer()
        .try_init();
}
